---
deployment:
  tasks:
    - export DEPLOYPATH=/home/enervn32/public_html/
    - export CSSPATH=/home/enervn32/public_html/css/
    - export JSPATH=/home/enervn32/public_html/js/
    - export FILEPATH=/home/enervn32/public_html/file/
    - /bin/cp public/* $DEPLOYPATH
    - /bin/cp public/css/* $CSSPATH
    - /bin/cp public/file/* $FILEPATH
    - /bin/cp public/js/* $JSPATH