---
deployment:
  tasks:
    - export DEPLOYPATH=/home/enervn32/public_html/
    - /bin/cp -r public/* $DEPLOYPATH
    - /bin/rename -f 's/\.product.php$/\.php/' /home/enervn32/public_html/index.product.php